### PR TITLE
revert to gradle 2.0.0, eliminate conflicting dependencies most notab…

### PR DESCRIPTION
**Pull request by tgshanahan**
Vlad,
When trying to run tests I ran into conficting jar load for bouncy castle which generated NoSuchMethod classloader issues.   To resolve these I explicitly eliminated duplicate dependendency loading via gradle 'excludes'.   Since I am relatively new to gradle, I look to you to define best practices so that jar dependencies are gracefully resolved.  Your feedback is appreciated

### CODE REVIEW

**Comment by skynet67** [comment]
Tim, what version of Android Studio are you using? I have just tried to use build:gradle:2.0.0 for running test app and building tests. I have no problems with dependencies.

https://www.dropbox.com/s/rj5r3lv4azd7y9h/fitpay_tests.jpg
https://www.dropbox.com/s/var3uia6t7imtzl/fitpay_app.jpg

Can you give me build errors or anything else that can be helpfull to find a problem

**Comment by tgshanahan** [comment]
I am using Android Studio 2.0.   I have no doubt that your particular installation is building and working find.  Mine, however, does not.  The main issue is that robo electric (testCompile) loads one version of bouncy castle while (compile) load another.  Details are below.   When running tests, the classloader is unfortunately loading the bcprov-jdk16 version which does not have some methods used in the encryption.  The result is a NoSuchMethod found error.  In my experience, classloader behavior is non-deterministic and issues that arise need to be addressed to get stability across a development team and build environment.

Overall, it is a noted best practice to manage gradle transitive dependencies - see: https://docs.gradle.org/current/userguide/dependency_management.html
However, as stated in this article, manual resolution as I have provided does not scale to larger projects.   Do you have a better suggestion?

Main dependencies:
default - Configuration for default artifacts.
+--- com.android.support:support-annotations:23.3.0
+--- com.android.support:appcompat-v7:23.3.0
|    +--- com.android.support:support-vector-drawable:23.3.0
|    |    \--- com.android.support:support-v4:23.3.0
|    |         \--- com.android.support:support-annotations:23.3.0
|    +--- com.android.support:animated-vector-drawable:23.3.0
|    |    \--- com.android.support:support-vector-drawable:23.3.0 (*)
|    \--- com.android.support:support-v4:23.3.0 (*)
+--- com.squareup.retrofit2:retrofit:2.0.0-beta4
|    \--- com.squareup.okhttp3:okhttp:3.0.1
|         \--- com.squareup.okio:okio:1.6.0
+--- com.squareup.retrofit2:converter-gson:2.0.0-beta4
|    +--- com.squareup.retrofit2:retrofit:2.0.0-beta4 (*)
|    \--- com.google.code.gson:gson:2.4
+--- com.squareup.okhttp3:logging-interceptor:3.1.2
**+--- org.bouncycastle:bcprov-jdk15on:1.54**
+--- com.nimbusds:nimbus-jose-jwt:4.12
|    +--- net.jcip:jcip-annotations:1.0
|    +--- net.minidev:json-smart:1.3.1
|    \--- commons-io:commons-io:2.4
+--- com.pusher:pusher-java-client:1.0.2
|    +--- org.slf4j:slf4j-log4j12:1.7.5
|    |    +--- org.slf4j:slf4j-api:1.7.5
|    |    \--- log4j:log4j:1.2.17
|    +--- org.java-websocket:java-websocket:1.3.1
|    \--- org.slf4j:slf4j-api:1.7.5
+--- com.github.orhanobut:logger:1.12
+--- io.reactivex:rxjava:1.1.2
+--- io.reactivex:rxandroid:1.1.0
\--- me.alexrs:prefs:1.1.0
 

Test compile dependencies:
+--- org.robolectric:robolectric:3.0
|    +--- org.robolectric:robolectric-annotations:3.0
|    +--- org.robolectric:robolectric-resources:3.0
|    |    +--- org.robolectric:robolectric-utils:3.0
|    |    |    +--- org.robolectric:robolectric-annotations:3.0
|    |    |    \--- com.google.android.apps.common.testing.accessibility.framework:accessibility-test-framework:1.0
|    |    +--- org.robolectric:robolectric-annotations:3.0
|    |    \--- com.ximpleware:vtd-xml:2.11
|    +--- org.robolectric:robolectric-utils:3.0 (*)
|    +--- org.robolectric:shadows-core:3.0
|    |    +--- org.robolectric:robolectric-annotations:3.0
|    |    +--- org.robolectric:robolectric-utils:3.0 (*)
|    |    +--- org.robolectric:robolectric-resources:3.0 (*)
|    |    +--- com.ibm.icu:icu4j:53.1
|    |    \--- com.almworks.sqlite4java:sqlite4java:0.282
**|    +--- org.bouncycastle:bcprov-jdk16:1.46**
... more

**Comment by skynet67** [comment]
Could you try to install and try to build with:
Android SDK Platform-tools 24 rc2
Android SDK Build-tools 24 rc3

**Comment by tgshanahan** [comment]
I do not believe that that activity provides any benefit.  Per the published best practices, we need a transitive dependency management strategy and implementation.  This is a first pass, do you have any experience which would indicate that another strategy is better?  If not, lets move forward

**Comment by skynet67** [comment]
Can you provide error stacktrace and did you update these files http://stackoverflow.com/a/6481658/957954 ?

I have just tried to make a install from scratch:

1) Android Studio 2.0:
---
Android SDK Tools 25.1.1
Android SDK Platform-tools 23.1
Android SDK Build-tools  23.0.3
---
Android API SDK 23
---
Android Support Repository 30
Android Support Library 23.2.1
Google Play services 29
Google Repository 25

2) Java:
---
 jdk1.8.0_92 (with files updates http://stackoverflow.com/a/6481658/957954 )

3) app (cloned bluetooth brach with few chagnes in project build.gradle files): 
classpath 'com.android.tools.build:gradle:2.0.0'
buildToolsVersion "23.0.3"

Test have passed

**Comment by tgshanahan** [comment]
I have the unlimited strength encryption files installed.

Without the changes I made, both myself and Eric get test failures when running gradle at the command line via './gradlew clean test'   With the beta1 gradle library the error occurs because maven central does NOT contain the asset:


eric [3:34 PM] 
[1006] epeers@megamouse:~/fitpay/fitpay-android> ./gradlew clean test

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'fitpay-android'.
> Could not resolve all dependencies for configuration ':classpath'.
  > Could not find com.android.tools.build:gradle:2.1.0-beta1.
    Searched in the following locations:
        https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.1.0-beta1/gradle-2.1.0-beta1.pom
        https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.1.0-beta1/gradle-2.1.0-beta1.jar
    Required by:
        :fitpay-android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.907 secs
[1007] epeers@megamouse:~/fitpay/fitpay-android>

**Pull request merged**
